dist: bionic

language: node_js

node_js:
  - lts/*

env:
  global:
    - FORCE_COLOR=true
    - NODE_ENV=production

stages:
  - name: test-stage
    if: type IN (pull_request) OR tag =~ [0-9]+\.[0-9]+\.[0-9]+

jobs:
  include:
    - stage: test-stage
      name: "test job"
      script: .travis/travis.sh
